version: 2
jobs:
  build:
    docker:
      - image: zenika/kotlin:1.3-jdk8
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            ./gradlew test
      - run:
          name: run linter
          command: |
            ./gradlew lintKotlin